export { default as HeroSection } from './HeroSection';
export { default as AboutSection } from './AboutSection';
export { default as ExperienceSection } from './ExperienceSection';
export { default as ProjectsSection } from './ProjectsSection';
export { default as SkillsSection } from './SkillsSection';
export { default as LeadershipSection } from './LeadershipSection';
export { default as EducationSection } from './EducationSection';
export { default as CertificationsSection } from './CertificationsSection';
export { default as ContactSection } from './ContactSection';
